import re
from enum import Enum
from typing import NamedTuple, Optional, List, Dict

from sqlalchemy import Boolean

# Chart Types 
class ChartType(Enum):
    SYMBOL_MAP = "SymbolMap"
    FILLED_MAP = "filledMap"
    LINE = "Line"
    AREA = "Area"
    PIE = "Pie"
    HIGHLIGHTED_TABLE = "Square"
    PIVOT_TABLE = "PivotTable"
    BAR = "Bar"
    HORIZONTAL_BAR = "HorizontalBar"
    VERTICAL_BAR = "VerticalBar"
    STACKED_VERTICAL_BAR = "StackedVerticalBar"
    STACKED_HORIZONTAL_BAR = "StackedHorizontalBar"
    TEXT_TABLE = "TextTable"
    TREE_MAP = "TreeMap"
    SLICER = "Slicer"
    TEXT_BOX = "TextBox"
    BAR_AND_AREA = "Bar & Area"
    BAR_AND_LINE = "Bar & Line"
    SCATTER = "ScatterPlot"
    MIXED_CHART = "MixedChart"
    AUTOMATIC = "Automatic"
    MULTIPOLYGON = "Multipolygon"
    DEFAULT_DASHBOARD_NAME = "UNTITLED"
    DONUT_CHART = "Donut"
    BUBBLE_CHART ="Bubble_chart"
    CIRCLE = "Circle"
    WATER_FALL = "WaterFallChart"
    GANTT_BAR = "Gantt_bar"
    SQUARE = "Square"
    AREA_AND_LINE = "Area & Line"
    LINE_AND_AREA = "Line & Area"
    BULLET_CHART = "Bullet_Chart"
    POLYGON_WITH_TABLE = "Polygon_with_table"
    POLYGON = "Polygon"
    SINGLE_CARD = "Single_Card"
    MULTIPLE_CARDS = "Multiple_Cards"
    TEXT = "Text"
    DONUT_WITH_CARD = "Donut_with_card"
    SHAPE = "Shape"
#File Status
class FileStatus(Enum):
    SUCCESS = "success"
    FAILURE = "failure"
    ERROR = "error"

#Operation Status
class OperationStatus(Enum):
    SUCCESS = "success"
    FAILURE = "failure"
#Server Status 
class ServerStatus(Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"

class ComplexityTypeEnum(str, Enum):
    SIMPLE = "Simple"
    MEDIUM = "Medium"
    COMPLEX = "Complex"
    SUPER_COMPLEX = "Super Complex" 
class PriorityEnum(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"

class MigrationEnum(str, Enum):
    yes = "Yes"
    no = "No"
    
class ReportStatusEnum(str, Enum):
    UN_ASSIGNED = "Un Assigned"
    ASSIGNED = "Assigned"
    ANALYSIS_COMPLETED = "Analysis Completed"
    DAX_CALCULATION_COMPLETED = "DAX Calculation Completed"
    DAX_CALCULATION_FAILED = "DAX Calculation Failed"
    SEMANTIC_MODEL_COMPLETED = "Semantic Model Completed"
    SEMANTIC_MODEL_FAILED = "Semantic Model Failed"
    MIGRATION_STARTED = "Migration Started"
    MIGRATED = "Migrated"
    MIGRATION_FAILED = "Migration Failed"
    UNIT_TESTING_COMPLETED = "Unit Testing Completed"
    UAT_COMPLETED = "UAT Completed"
    DEPLOYED = "Deployed"    
    UNIT_TESTING_FAILED = "Unit Testing Failed"
    UAT_FAILED = "UAT Failed"
    DAX_CALCULATION_IN_PROGRESS = "DAX Calculation In Progress"
    UNIT_TESTING_IN_PROGRESS = "Unit Testing In Progress"
    UAT_IN_PROGRESS = "UAT In Progress"
    ANALYSIS_FAILED = "Analysis Failed"
    ANALYSIS_PENDING = "Analysis Pending"
    ANALYSIS_SKIPPED = "Analysis Skipped"
    FETCHED = "Fetched"
    INFO = "Info"
    SUCCESS = "success"
    FAILED = "failed"

class DiscoverSiteStatus(Enum):
    INITIATED = "Initiated"
    STARTED = "Started"
    IN_PROGRESS = "InProgress"
    COMPLETED = "Completed"
    FAILED = "Failed"


#  Server Authentication 
class ServerAuthType(str, Enum):
    CREDENTIALS = "CREDENTIALS"
    PAT = "PAT"

class RoleEnum(str, Enum):
    ADMIN = "Admin"
    MANAGER = "Manager"
    DEVELOPER = "Developer"

class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
#  Datasource Types 
class Datasource_types(Enum):
    MSSQL = "mssql"
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    SQLITE = "sqlite"
    ORACLE = "oracle"
    ALLOWED_TYPES = ["mssql", "postgresql", "mysql", "sqlite", "oracle"]


# Server Type 
class ServerType(str, Enum):
    ONPREMISE = "ONPREMISE"
    CLOUD = "CLOUD"


# Important Keys
class ImportantKeys(Enum):
    PASSWORD = "password"
    KEYS_TO_CHANGE_DTYPES_TO_STR = [
        "id", "_sa_instance_state", "created_at", "updated_at"
    ]


# Dashboard Constants
class Dashboard(Enum):
    DASHBOARD = ".//dashboard"
    NAME = "name"
    DS_DEPENDENCIES = ".//datasource-dependencies"
    ZONE = ".//zone"
    COLUMN = ".//column"
    STYLE_FORMAT = ".//style-rule/format"
    ZONE_STYLE = ".//zone-style"
    VIEW = ".//view"
    ENCODINGS = ".//encodings/*"


# Datasource Constants
class Datasource(Enum):
    DSS = "datasources"
    Datasources = "Datasources"
    DS = ".//datasource"
    DATASOURCES = ".//datasources"
    COLUMN = "column"
    CALC = "calculation"
    CALC_IN_DS = "Calculations"
    FORMULA = "formula"
    DATATYPE = "datatype"
    NAME = "name"
    CAPTION = "caption"
    FILTERS = "Filters"
    NAMED_CONNECTIONS = "./connection/named-connections"
    RELATION = ".//relation"
    COLS_MAP = ".//cols/map"
    CONNECTION = "./connection"
    CONNECTION_RELATION = "./connection/relation"
    META_RECORD = ".//metadata-record"
    RELATIONSHIP = ".//relationship"
    FIRST_END_POINT = "./first-end-point"
    SECOND_ENC_POINT = "./second-end-point"
    EXPRESSION = "./expression"
    FILTER = ".//filter"
    COLUMNS_COLUMN = "columns/column"
    EXTRACT = ".//extract"
    METADATA_RECORD_CLASS = ".//metadata-record[@class='column']"
    REMOTE_NAME = "remote-name"
    LOCAL_TYPE = "local-type"
    PARENT_NAME = "parent-name"
    AGGREGATION = "aggregation"
    OBJECT_ID = "object-id"
    OBJECT_TAG = ".//object"
    ID = "id"
    CONNECTION_CLASS = "class"
    CONNECTION_DIRECTORY = "directory"
    TABLE_NAME = "table_name"
    ROLE = "role"
    LOCAL_NAME = "local-name"

# General Keys 
class GeneralKeys(Enum):
    NAME = "name"
    PATH = "path"
    COLUMN = "column"
    TYPE = "type"
    ROLE = "role"
    DATATYPE = "datatype"
    CLASS = "class"
    SIZE = "size"
    Datasources = "datasources"
    Datasource = "datasource"
    DS_DEPENDENTIES = "datasource-dependencies"
    ZONES = "zones"
    CALC = "calculation"
    FORMULA = "formula"
    CAPTION = "caption"
    WorkSheets ="Worksheets"
    CONNECTION = "connection"
    NAMED_CONNECTION = "named-connection"
    FILE_NAME = "filename"
    LOCAL_NAME = "local-name"
    LOCAL_TYPE = "local-type"
    GROUP_FILTER = "groupfilter"
    PARAMETERS = "Parameters"
    VALUE = "value"
    KEY = "key"
    OBJECT_ID = "object-id"
    EXPRESSION = "expression"
    NULL = "NULL"
    OP = "op"
    TABLE = "table"
    DB_NAME = "dbname"
    COLUMN_INSTANCES = "column-instances"
    COLUMN_INSTANCE = "column-instance"
    FILTERS = "filters"
    SLICES = "slices"
    ATTR = "attr"
    MARK = "mark"
    ENCODINGS = "encodings"
    STYLES = "styles"
    STYLE = "style"
    ROWS = "rows"
    COLS = "cols"
    PANES = "panes"
    PARAM = "param"
    TYPE2 = "type-v2"
    VIEW = "view"
    COLUMNS = "columns"
    LAYOUT = "layout"
    UNTITLED = "Untitled Dashboard"
    DATASOURCE_COUNT = "datasource_count"
    STATUS = "status"
    TWB_FILE = ".twb"
    CHART_TYPE = "chart_type"
    CHART_TYPES = "chart_types"
    ERROR = "error"
    DATE_TIME_SET = {'date', 'datetime'}
    QUANTITATIVE = "quantitative"
    TWB_FILE_EXTENSION = ".twb"  # Deprecated: Use TWB_FILE instead
    NO_COLUMNS_AVAILABLE = "No columns available"
    UNKNOWN = "unknown"
    COLUMN_NAME_KEY = "column_name"
    MAPPING_VALUE_KEY = "mapping_value"
    TABLE_COLUMN_SEPARATOR = "].["
    TABLE_COLUMN_PATTERN = re.compile(r'\[(.*?)\]\.\[([^\]]*)\]')
    UNNAMED_TABLE = "Unnamed Table"
    UNNAMED_COLUMN = "Unnamed Column"
    FONT_NAME = 'Arial'
    DEFAULT_FONT_SIZE_PT = 11
    DOC_TITLE = "Summary"
    TABLE_HEADERS_VISUALS = ['Report Name', 'Visual Name', 'Visual Type']
    MIGRATION_AUTOMATIC = "Biport"
    MIGRATION_MANUAL = "Manual"
    DASHBOARDS = "Dashboards"
    UNTITLED_DASHBOARDS = "untitled dashboards"
    Dashboards = "Dashboards"
    Columns_and_Datatypes = "Columns and Data Types"
    DEFAULT_Schema = "Default Schema"
    CONNECTION_DETAILS = "connection_details"
    UNKNOWN_TYPE = "Unknown Type"
    CALCULATIONS = "Calculations"
    DASHBOARD_JSON = "dashboard.json"
    SUPPORTED_FILE_EXTENSION = ".twb"
    TOOLTIP = 'tooltip'
    QK = 'qk'
    NK = 'nk'
    REFLINE = "refline"
    QUANTATIVE = "quantitative"
    ORDINAL = "ordinal"
    DEFAULT_DASHBOARD_NAME = "UNTITLED"
    UNNMAED_COLUMN = "Unnamed column"
    CONNECTION_TYPE = "connection_type"
    HYPER = "hyper"
    EXTRACT = "Extract"
    LIVE = "Live"
    EXTRACT_CLASS = "extract_class"
    UNKNOWN_DATASOURCE = "unknown datasource"
    HYPER_FILE = "Hyper file"
    EXCEL = "Excel"
    CSV_OR_TEXT_FILE = 'CSV or Text File'
    CALCULATION_ = "Calculation_"
    NOT_INCLUDING_WHILE_FETCHING_DIMENTIONS = ["mode", "param" ]
    Z_DEFAULT_ZERO = "0.00"
    LAYOUTS = "layouts"
    ID = "id"
    POSITION = "position"
    X = "x"
    Y = "y"
    Z = "z"
    H = "h"
    W = "w"
    MEASURE = "measure"
    TEXT_BOX_VISUAL = "text_box_visual"
    TEXT = "text"

class FilterValues(Enum):
    YR = "yr"
    QR = "qr"
    MN = "mn"
    WK = "wk"
    DY = "dy"
    TYR = "tyr"
    TQR = "tqr"
    TMN = "tmn"
    TWK = "twk"
    TDY = "tdy"
    YEAR = "Year"
    MONTH = "Month"
    QUARTER = "Quarter"
    COUNT = "Count"
    AVERAGE = "Average"
    DAY = "Day"
    SUM = "sum"
    CNT = "cnt"
    USR = "usr"
    AVG = "avg"
    MAX = "max"
    MIN = "min"
    MED = "med"
    STD = "std"
    VAR = "var"
    PRC = "prc"
    CTD = "ctd"
    ATTR = "attr"
    WD = "wd"


# Table Constants
class TableConstants:
    COLUMNS_KEY = "Columns and Data Types"
    TYPE_KEY = "Type"
    TABLE_TYPE_DEFAULT = "table"


# Worksheet Constants 
class WorkSheet(Enum):
    PANES_PANE = ".//panes/pane"
    PANE = ".//pane"
    PANES = ".//panes"
    ENCODINGS = ".//encodings"
    ENCODING_COLOR = ".//encodings/color"
    ENCODING_TEXT = ".//encodings//text"
    PANES_PATH_ATT = ".//encodings/path"
    ALL_ENCODINGS = ".//panes/pane//encodings/*"
    ENCODINGS_IN_ALL = ".//encodings/*"
    ROWS = ".//rows"
    COLS = ".//cols"
    DS_COL_INSTANCES = ".//datasource-dependencies/column-instance"
    DS_COLS = ".//datasource-dependencies/column"
    NAME = "name"
    COLUMN = "column"
    TYPE = "type"
    ROLE = "role"
    DATATYPE = "datatype"
    COLUMN_INSTANCE = ".//column-instance"
    MARK = ".//mark"
    CLASS = "class"
    MAP_SOURCES = ".//mapsources"
    LONGITUDE = "Longitude"
    LATITUDE = "Latitude"
    SIZE = "size"
    AUTOMATIC = "Automatic"
    WORKSHEETS = ".//worksheet"
    COLS_MAP = ".//cols/map"
    FILTER = ".//filter"
    SLICES_COLUMN = ".//slices/column"
    STYLE_RULE_FORMAT = ".//style-rule/format"
    STYLE_RULE = ".//style-rule"
    REFERENCE_LINE = ".//reference-line"
    


# Complexity Levels
class ComplexityLevel(Enum):
    SIMPLE = "Simple"
    MEDIUM = "Medium"
    COMPLEX = "Complex"
    SUPER_COMPLEX = "Super complex"


class TableauXMLTags(Enum):
    LOD = "lod"
    AXIS = "axis"
    NAME = "name"
    TEXT = "text"
    VIEW = "view"
    ATTR = "attr"
    FIELD = "field"
    SCOPE = "scope"
    CLASS = "class"
    TITLE = "title"
    TABLE = "table"
    VALUE = "value"
    COLOR = "color"
    FORMAT = "format"
    COLUMN = "column"
    ELEMENT = "element"
    TOOLTIP = "tooltip"
    ENCODING = "encoding"
    STYLE_RULE = "style-rule"
    LOCAL_TYPE = "local-type"
    LOCAL_NAME = "local-name"
    PANES = ".//panes"
    PARENT_NAME = "parent-name"
    REMOTE_NAME = "remote-name"
    CALCULATION = "calculation"
    AGGREGATION = "aggregation"
    COMPUTED_SORT = "computed-sort"
    COLUMN_INSTANCE = ".//column-instance"
    LAYOUT_OPTIONS = "layout-options"
    FORMATTED_TEXT = "formatted-text"
    SIZE = "size"
    USING = "@using"
    DIRECTION = "@direction"
    ROWS = ".//rows"
    COLS = ".//cols"
    PANE = ".//pane"
    MARK = ".//mark"
    STYLE = ".//style"
    ZONES = ".//zones"
    ZONE = ".//zone"
    RUN_TAG = ".//run"
    FILTER = ".//filter"
    GROUP_FILTER = ".//groupfilter"
    WORKSHEET = ".//worksheet"
    ENCODINGS = ".//encodings"
    DASHBOARD = ".//dashboard"
    DATASOURCE = ".//datasource"
    DATASOURCE_DEPENDENCIES = ".//datasource-dependencies"
    TITLE_RUN = ".//layout-options/title/formatted-text/run"
    METADATA_RECORDS = ".//metadata-record[@class='column']"
    WINDOWS = ".//window"
    WORKSHEETS_DIMENSIONS_WITH_NAMES = "worksheets_with_zones"
    TAB_ORDER = "tabOrder"
    CELL = "cell"
    NORMAL = "normal"
    NONE = "none"
    ACTIONS = ".//action"
    FONT_STYLE = "font-style"
    FONT_WEIGHT = "font-weight"
    FONT_SIZE = "font-size"
    FONT_FAMILY = "font-family"
    FONT_COLOR = "font-color"
    UNDERLINE = "underline"
    BOLD = "bold"
    ITALIC = "italic"
    IS_ITALIC = "is_italic"
    TEXT_DECORATION = "text-decoration"
    LABEL = "label"
    RUN = "run"
    LAYOUT_FORMATTED_TEXT = ".//layout-options/title/formatted-text"
    FORMATTED_TEXT_RUN = "formatted-text/run"
    FORMAT_TAG = ".//format"
    STYLE_RULES = ".//table/style/style-rule"
    TEXT_BOX_TEXT = ".//table/view/datasource-dependencies/column/calculation"
    MARK_TEXT = "mark"
    PALETTE = "palette"
    COLOR_PALETTE = "color-palette"
    BORDER_COLOR = "border-color"
    BORDER_WIDTH = "border-width"
    BG_COLOR = "background-color"
    PARAMS = ".//param"
    TARGET = "target"
    FORMATTED_TEXT_RUN_TAG = ".//formatted-text/run"
    CALCULATION_ = "Calculation_"
    CAPTION = "caption"
    FONT_NAME = "fontname"
    FONTCOLOR = "fontcolor"
    FONT_ALIGNMENT = "fontalignment"
    BACKGROUND = "background"
    IS_UNDERLINED = "is_underlined"
    BACKGROUND_COLOR = "background-color"
    FONTSIZE = "fontsize"
    BORDER_STYLE = "border-style"
    MAX_HEIGHT = "maxheight"
    MAX_WIDTH = "maxwidth"
    MEASURE_NAMES = ":Measure Names"
    MULTIPLE_VALUES = "Multiple Values"
    GROUPFILTER = "groupfilter"
    LEVEL = "level"
    MEMBER = "member"
    FUNCTION = "function"
    TABLEAU_OBJECT_ID = "__tableau_internal_object_id__"
    COLUMN_INSTANCES = "column-instances"
    TYPE_V2 = "type-v2"
    ZONE_STYLE_FORMAT = "zone-style/format"
    ID = "id"
    TEXT_FORMAT = "text-format"
    PARAM = "param"
    URL = "url"
    MIN = "min"
    MAX = "max"
    INCLUDED_VALUES = "included-values"
    END = "end"
    UI_TOP_BY_FIELD = "ui-top-by-field"
    UI_PATTERN_TYPE = "ui-pattern_type"
    UI_PATTERN_TEXT = "ui-pattern_text"
    CONTAINS = "contains"
    STARTS_WITH = "starts-with"
    EXACT_MATCH = "exact-match"
    UNION = "union"
    FIRST_PERIOD = "first-period"
    LAST_PERIOD = "last-period"
    PERIOD_TYPE_V2 = "period-type-v2"
    PERIOD_ANCHOR = "period-anchor"
    RELATIVE_DATE = "relative-date"
    UI_ENUMERATION = "ui-enumeration"
    INCLUDE_FUTURE = "include-future"
    INCLUDE_NULL = "include-null"
    COLUMNS_TAG = ".//column"
    CARDS_TAG = ".//card"
    ZONE_IN_ZONES = "./zones/zone"
    DATASOURCE_NAME = "datasource"
    SHARED_VIEWS = ".//shared-views"
    PARAM_DOMAIN_TYPE = "param-domain-type"

class FilterTypes(Enum):
    CATEGORICAL = "Categorical"
    ADVANCED = "Advanced"
    RELATIVEDATE = "RelativeDate"
    TOP_N = "Top N"

class ComparisonKind(Enum):
    """
    Power BI ComparisonKind enum values for filter comparisons.
    Maps to Power BI comparison operators:
    - 0: Equals ("is")
    - 1: NotEquals ("is not")
    - 2: GreaterThanOrEqual ("is on or after")
    - 3: GreaterThan ("is after")
    - 4: LessThanOrEqual ("is on or before")
    - 5: LessThan ("is before")
    - 6: Contains
    - 7: DoesNotContain
    - 8: StartsWith
    - 9: DoesNotStartWith
    - 10: IsBlank ("is blank")
    - 11: IsNotBlank ("is not blank")
    """
    EQUALS = 0
    NOT_EQUALS = 1
    GREATER_THAN_OR_EQUAL = 2
    GREATER_THAN = 3
    LESS_THAN_OR_EQUAL = 4
    LESS_THAN = 5
    CONTAINS = 6
    DOES_NOT_CONTAIN = 7
    STARTS_WITH = 8
    DOES_NOT_START_WITH = 9
    IS_BLANK = 10
    IS_NOT_BLANK = 11
    
class PowerBIReportKeys(Enum):
    NAME = "name"
    LAYOUTS = "layouts"
    SINGLE_VISUAL = "singleVisual"
    ACTIVE = "active"
    QUERYREF = "queryRef"
    CONFIG = "config"
    DISPLAY_NAME = "displayName"
    COLUMN_PROPERTIES = "columnProperties"
    DISLAY_OPTION = "displayOption"
    ORDINAL = "ordinal"
    X = "X"
    Y = "Y"
    Y2 = "Y2"
    ROWS = "Rows"
    COLUMNS = "Columns"
    SIZE = "Size"
    VALUES = "Values"
    GROUP = "Group"
    DETAILS = "Details"
    SERIES = "Series"
    CATEGORY = "Category"
    TOOLTIPS = "Tooltips"
    VISUAL_TYPE = "visualType"
    PROJECTIONS = "projections"
    VERSION = "Version"
    FROM = "From"
    SELECT = "Select"
    PROTOTYPE_QUERY = "prototypeQuery"
    DRILL_FILTER_OTHER_VISUAL = "drillFilterOtherVisuals"
    HAS_DEFAULT_SORT = "hasDefaultSort"
    ENTITY = "Entity"
    TYPE = "Type"
    NAME_IN_FROM_LIST = "Name"
    SUM = "Sum"
    MAX = "Max"
    VISUAL_CONTAINERS = "visualContainers"
    FILTERS = "filters"
    HEIGHT = "height"
    WIDTH = "width"
    EMPTY_DICTIONARY = "{}"
    EMPTY_SQUARE = "[]"
    DIMENSIONS = {"x":"x","y":"y","z":"z","h":"height","w":"width"}
    OBJECTS = "objects"
    COLOR = "color"
    FONT_FAMILY = "fontFamily"
    VC_OBJECTS = "vcObjects"
    PARAMETERS = "parameters"
    X_DIMENSION = "x"
    Y_DIMENSION = "y"
    Z_DIMENSION = "z"
    AVG = "Avg"
    MEDIAN = "Median"
    STANDARD_DEVIATION = "Standard deviation"
    MIN = "Min"
    VARIANCE = "Variance"
    COUNTNONNULL = "CountNonNull"
    COUNT = "Count"
    W = "w"
    H = "h"
    STDDEV = 'Std'
    HOW_CREATED = "howCreated"
    RESOURCE_PACKAGES = "resourcePackages"
    SECTIONS = "sections"
    PODS = "pods"
    REPORT_FOLDER = ".Report"
    STATIC_RESOURCES = "StaticResources"
    REGISTERED_RESOURCES = "RegisteredResources"
    EXPRESSION = "expression"
    FILTER = "filter"
    CONDITION = "Condition"
    IN = "In"
    TYPE_= "type"
    WHERE = "Where"
    EXPRESSIONS = "Expressions"
    CACHED_DISPLAY_NAMES = "cachedDisplayNames"


class PowerBITemplateKeys(Enum):
    VISUAL_TYPE = "visual_type"
    PROJECTIONS_DATA = "projections_data"
    TABLES_LIST = "tables_list"
    TABLE_NAME = "table_name"
    COLUMN = "column"
    FILTER = "filter"
    WORKSHEET_NAME = "worksheet_name"
    DIMENSIONS = "dimensions"
    TABLE_COLUMNS = "table_columns"
    COLUMN_VALUE = "column_value"
    UNIQUE_ID = "unique_id"
    COLUMN_DATA = "column_data"
    DATA_TYPE = "data_type"
    AGGREGATION = "aggregation"
    COLUMN_NAME = "column_name"
    COLUMN_CAPTION = "column_caption"
    FORMAT_STRING = "format_string"
    SUMMARIZE_BY = "summarize_by"
    SOURCE_COLUMN = "source_column"
    LINEAGE_TAG = "lineage_tag"
    TEXT_BOX = "textBox"
    OBJECTS = "objects"
    VARIATION = "variation"
    LOCAL_DATE_TABLE_REF = "local_date_table_ref"
    RELATIONSHIP_ID = "relationship_id"
    FORMULA = "formula"
    CONNECTION_TYPE = "connection_type"
    DIRECTORY = "directory"
    SERVER = "server"
    DATABASE = "database"
    TOOLTIP = "tooltip"
    IS_TOOLTIP_SOURCE = "is_tooltip_source"
    SLICER = "Slicer"
    ZONES = "zones"
    ZONE = "zone"
    SCHEMA = "schema"
    WAREHOUSE = "warehouse"
    NAME = "name"
    v_http_path = "v_http_path"
    VCOBJECTS = "vcObjects"
    COLUMN_TYPE = "column_type"
    CALCULATIONS = "Calculations"
    PARAMETERS = "Parameters"
    MEASURE = "measure"
    TYPE = "type"
    TEXT_DETAILS = "text_details"
    ZONE_STYLES = "zone_styles"
    DIMENSION = "dimension"
    SLICER_TYPE = "slicer_type"
    COLUMN_DATATYPE = "column_datatype"
    GROUP_NAME = "group_name"
    GROUP_TYPE = "group_type"
    GROUP = "group"
    BASE_COLUMN = "base_column"
    DATA_FORMAT = "data_format"
    IMAGE_NAME = "image_name"
    CLASS = 'class'
    GROUPFILTER = "groupfilter"
    VALUES_LIST = "values_list"
    COLUMN_GROUPFILTER_MAPPING = "column_groupfilter_mapping"
    INCLUDED_VALUES = "included-values"
    ATTRIBUTES = "attributes"
    SUBQUERY_EXPRESSIONS = "subquery_expressions"
    FILE_PATH = "file_path"
    CUSTOM_SQL_QUERY = "custom_sql_query"
    CUSTOM_SQL_TYPE = "custom_sql_type"
    DATASOURCE_NAME = "datasource"
    DATATYPE = "datatype"
    PARAMETER_TYPE = "parameter_type"
    STRING = "string"
    INTEGER = "integer"
    BASIC = "Basic"
    DATE = "date"
    DATE_COLUMN = "Date"
    DATE_TIME = "datetime"
    BOOLEAN = "boolean"
    DISPLAY_AS = "Display As"
    REAL = "real"
    ANY = "any"
    MEASURE_ADJUSTMENT = "meausre_adjustment"
    NTH_ITERATION = "nth_iteration"
    INITIAL_DIMENSION = "initial_dimension"

class PowerBIChartTypes(Enum):
    LINE_CHART = "lineChart"
    AREA = "areaChart"
    CLUSTERED_COLUMN = "clusteredColumnChart"
    CLUSTERED_BAR = "clusteredBarChart"
    PIVOT_TABLE = "pivotTable"
    LINE_STACKED_COLUMN_COMBO_CHART = "lineStackedColumnComboChart"
    FILLED_MAP = "filledMap"
    MAP = "map"
    PIE = "pieChart"
    DONUT = "donutChart"
    SCATTER = "scatterChart"
    COLUMN_CHART = "columnChart"
    BAR_CHART = "barChart"
    TABLE_EX = "tableEx"
    TREE_MAP = "treemap"
    CUSTOM = "custom"
    TEXT_BOX = "textbox"
    SLICER = "slicer"
    CARD = "card"
    CARDS = 'cards'
    MULTIROWCARD = "multiRowCard"
    BITMAP = "bitmap"
    TEXT_SLICER = "textSlicer"


class VisualRequest(NamedTuple):
    worksheet_name: str 
    visual_type: str
    rows: Optional[List] = []
    cols: Optional[List] = []
    panes: Optional[List] = []
    filters: Optional[List] = []
    semantic_data: Dict = {}
    datasource_columns: Optional[List] = []
    worksheet_style_data: Optional[Dict] = {}
    worksheet_title_data: Optional[List] = {}
    tooltip_sheetname: Optional[str] = ""
    is_tooltip_source: Optional[Boolean] = False
    small_multiples: bool = False
    visual_filters: Optional[List] = []
    
class PowerBIObjectKeys(Enum):
    LINE_STYLES = "lineStyles"
    LEGEND = "legend"
    LABELS = "labels"
    CATEGORY_AXIS = "categoryAxis"
    VALUE_AXIS = "valueAxis"
    Y2_AXIS = "y2Axis"
    QUICK_FILTER = "quickFilter"
    SHOW = "show"
    DATA_POINT = "dataPoint"
    SWITCH_AXIS_POSITION = "switchAxisPosition"
    LABEL_PRECISION = "labelPrecision"
    SHOW_AXIS_TITLE = "showAxisTitle"
    TITLE_COLOR = "titleColor"
    TITLE_FONT_SIZE = "titleFontSize"
    TITLE_FONT_STYLE = "titleFontStyle"
    TITLE_FONT_WEIGHT = "titleFontWeight"
    TITLE_TEXT_DECORATION = "titleTextDecoration"
    LABEL_COLOR = "labelColor"
    TITLE_ITALIC = "titleItalic"
    TITLE_BOLD = "titleBold"
    TITLE_UNDERLINE = "titleUnderline"
    UNDERLINE = "underline"
    BOLD = "bold"
    ITALIC = "italic"
    TRUE = "true"
    FALSE = "false"
    COLOR = "color"
    FONT_FAMILY = "fontFamily"
    SHOW_MARKER = "showMarker"
    SHOW_LEGEND = "showLegend"
    AREA_SHOW = "areaShow"
    AREA_MATCH_STROKE_COLOR = "areaMatchStrokeColor"
    POSITION = "position"
    VALUE = "value"
    RIGHT = "right"
    LEFT = "left"
    CENTER = "center"
    FONT_ALIGNMENT = "fontalignment"
    PT = "pt"
    ONE = "1"
    TWO = "2"
    EMPTY = ""
    BG_COLOR = "background-color"
    FONT_STYLE = "fontStyle"
    FONTWEIGHT = "fontWeight"
    FONTSIZE = "fontSize"
    IS_BOLD = "is_bold"
    TEXT_DECORATION = "textDecoration"
    FONT_WEIGHT = "font-weight"
    HEADER = "header"
    LABEL = "label"
    PURE_WHITE = "#ffffff"
    PURE_BLACK = "#000000"
    MARKERS = "markers"
    TRANSPARENCY = "transparency"
    ENTITY = "Entity"
    PROPERTY = "Property"
    FILTER_VALUE = "filterValue"
    MIN = "min"
    MID = "mid"
    MAX = "max"
    MAP_STYLES = "mapStyles"
    MAP_THEME= "mapTheme"
    SHOW_LABELS = "showLabels"
    MAP_CONTROLS ="mapControls"
    AUTO_ZOOM ="autoZoom"
    SHOW_ZOOM_BUTTONS ="showZoomButtons"
    SHOW_LASSO_BUTTON ="showLassoButton"
    BORDER = "border"
    BACKGROUND = "background"
    TITLE = "title"
    TEXT = "text"
    FONTCOLOR = "fontColor"
    BACKCOLOR = "backColor"
    ALIGNMENT = "alignment"
    BACKGROUNDCOLOR = "backgroundColor"
    BORDERCOLOR = "borderColor"
    TITLEWRAP = "titleWrap"
    TEXT_STYLE = "textStyle"
    TEXT_RUNS = "textRuns"
    TEXT_ALIGNMENT = "horizontalTextAlignment"
    PARAGRAPHS = "paragraphs"
    GENERAL = "general"
    CATEGORY_LABELS = "categoryLabels"
    PROPERTIES = "properties"
    BUTTON = "button"
    ACTION = "action"
    SIMPLE_ID = "simple-id"
    UUID = "uuid"
    MODE = "mode"
    DATA = "data"    
    STYLE ="style"
    OUTSPACE_COLOR = "outspace_color"
    VALUES = "values"
    COLUMN_TYPE = "columnType"
    FILL = "fill"
    COLUMN_DATATYPE = "columnDataType"
    LABELSTYLE = "labelStyle"
    FORMAT_STRING = "formatString"
    ALIASIS = "Aliases"
    